version: "3"
services:
    app:
        depends_on:
            - mongo
        container_name: app
        restart: always
        build: .
        ports:
            - "3000:3000"
        links:
            - mongo
    mongo:
        container_name: mongo
        image: mongo:3.2
        volumes:
            - ./data:/data/db
        ports:
            - "27018:27017"